### ISSUE TITLE
Group Tracker

### ISSUE THREAD

**Issue by laylabmanley** [Boxnet-Media/boxnetjam#21]
Pretty simple script that should be given a string in the inspector via an exported variable and then keep track of all nodes in that group within an Area2D.

- [x] Create a `GroupTracker` script that extends `Area2D`.
- [x] The script should have an array of nodes and an exported variable called `group`
- [x] When a body enters the area, if it's in the group `group`, add it to the array
- [x] When a body leaves the area, it should be removed from the array
