### ISSUE TITLE
Create Player Script

### ISSUE THREAD

**Issue by laylabmanley** [Boxnet-Media/boxnetjam#24]
The player script should tie in all the following:
- [x] Camera should follow player #12 
- [x] Player should be able to rotate a `Hand` Node2D. A child of that node should be a flashlight #15 
- [x] Player should be able to move around! #6 

Blocked by #12 #15 #6

**Comment by laylabmanley** [comment]
Still needs #15, but work can start now.
