### ISSUE TITLE
Level Tracker

### ISSUE THREAD

**Issue by laylabmanley** [Boxnet-Media/boxnetjam#29]
Create a singleton that keeps track of all player data, this will likely also be used for saving if we ever get to that.

- [x] Create a singleton that to keep track of this data. Let's call it a script `global` that extends `Node`.
- [x] The singleton should have an array of preloaded nodes for levels (See https://docs.godotengine.org/en/3.0/getting_started/step_by_step/resources.html#loading-resources-from-code)
- [x] There should be a `current_level` variable that refers to the current indexed level in the code.
- [x] A `new_game()` function should be added to `global` that sets `current_level` to `0`
